name = "default"

[categories]
Location = [
    "haunted house",
    "spaceship",
    "medieval castle",
    "submarine",
    "airport security line",
    "wedding reception",
    "zombie apocalypse bunker",
    "circus tent",
    "high school reunion",
    "train station",
    "supermarket checkout",
    "jury duty waiting room",
    "pirate ship",
    "theme park ride",
    "library during a blackout",
    "emergency room",
    "secret underground lab",
    "boxing ring",
    "casino at 3 AM",
    "coffee shop on open mic night"
]

Job = [
    "optometrist",
    "divorce lawyer",
    "bartender",
    "coal miner",
    "wedding planner",
    "fortune teller",
    "astronaut",
    "stand-up comedian",
    "zookeeper",
    "taxidermist",
    "game show host",
    "stunt double",
    "pizza delivery driver",
    "air traffic controller",
    "mime",
    "tattoo artist",
    "bounty hunter",
    "pet psychic",
    "barista",
    "bus driver"
]

Relation = [
    "childhood friends",
    "stepmother and stepchild",
    "siblings",
    "spouses",
    "exes who just ran into each other",
    "grandparent and grandchild",
    "rival coworkers",
    "teacher and failing student",
    "best friends on a road trip",
    "two people on a disastrous blind date",
    "landlord and tenant",
    "private detective and client",
    "two actors in the same audition",
    "lifelong pen pals meeting in person",
    "two villains plotting world domination",
    "roommates who hate each other",
    "wedding officiant and nervous groom",
    "prisoner and warden",
    "magician and skeptical audience member",
    "pirate captain and rebellious crew member"
]

Object = [
    "a cursed amulet",
    "a broken time machine",
    "an empty suitcase",
    "a winning lottery ticket",
    "a talking parrot",
    "a suspicious-looking diary",
    "a golden key",
    "a mysterious potion",
    "a malfunctioning robot",
    "a clown wig",
    "a tattered treasure map",
    "a jar of fireflies",
    "a haunted doll",
    "a deck of tarot cards",
    "a snow globe with a tiny city inside",
    "a fake mustache",
    "a suitcase full of spaghetti",
    "a giant inflatable duck",
    "a detective's notebook",
    "a magic wand that only works sometimes"
]

Emotion = [
    "paranoid",
    "ecstatic",
    "heartbroken",
    "furious",
    "embarrassed",
    "overconfident",
    "apathetic",
    "terrified",
    "smug",
    "nostalgic",
    "jealous",
    "hopelessly romantic",
    "vengeful",
    "delirious from lack of sleep",
    "overwhelmed",
    "giddy with excitement",
    "suspicious",
    "deeply regretful",
    "conflicted",
    "proud but trying to hide it"
]

Situation = [
    "stuck in an elevator",
    "mistaken identity mix-up",
    "running from the law",
    "time travel gone wrong",
    "forced to work together despite hating each other",
    "winning a huge prize but not knowing what to do next",
    "stranded on a deserted island",
    "surviving a zombie outbreak",
    "sneaking into an exclusive party",
    "trapped in a dream",
    "about to confess a huge secret",
    "competing in a high-stakes game show",
    "realizing they’re in a simulation",
    "trying to cover up an embarrassing mistake",
    "training for a bizarre new job",
    "faking their way into a VIP event",
    "desperately trying to impress someone",
    "forced to babysit a hyperactive child",
    "stuck in a never-ending loop",
    "undercover at a villain’s lair"
]

Quirk = [
    "constantly quoting movies",
    "terrified of left-handed people",
    "believes they're a famous celebrity",
    "only speaks in rhymes",
    "thinks they're being followed by spies",
    "has a habit of collecting shiny objects",
    "can’t stop laughing at inappropriate moments",
    "obsessed with conspiracy theories",
    "always acts like they’re in a musical",
    "refuses to acknowledge modern technology",
    "believes they can talk to animals",
    "has a dramatic flair for the smallest things",
    "thinks they’re the chosen one",
    "always carries an umbrella, even indoors",
    "narrates their own life out loud",
    "insists on shaking hands after every sentence",
    "suffers from extreme stage fright",
    "believes they have magical powers",
    "has an over-the-top evil laugh",
    "treats everything like a high-stakes poker game"
]

Secret = [
    "they’re actually a time traveler",
    "they just committed a crime",
    "they’re in witness protection",
    "they were switched at birth",
    "they know the world is about to end",
    "they're hiding a talking animal",
    "they just found out they have a long-lost twin",
    "they’re pretending to be someone they’re not",
    "they secretly love their worst enemy",
    "they’ve been cursed by a witch",
    "they’re actually royalty",
    "they accidentally started a cult",
    "they’re an undercover spy",
    "they found a treasure map but won’t share it",
    "they have superpowers they can’t control",
    "they’re trying to escape an arranged marriage",
    "they know who really committed a famous crime",
    "they have a list of people they want revenge on",
    "they’re an alien in disguise",
    "they just inherited a fortune but don’t want anyone to know"
]
